### ISSUE TITLE
Model code

### ISSUE THREAD

**Issue by alexpostnikov** [CHENGY12/DisDis#1]
Are you planning to show the model & training code?

**Comment by CHENGY12** [comment]
Thanks for your attention!  This repo has contained all training code and our trained models. The model can be found in  DisDis/experiments/pedestrians/models/, and the main script of the training code is DisDis/trajectron/train.py. Please do not hesitate to contact me if you have any other questions.

**Comment by alexpostnikov** [comment]
Oh, I see.
Thanks!
