### ISSUE TITLE
Question about visualization in your paper?

### ISSUE THREAD

**Issue by Xiejc97** [CHENGY12/DisDis#2]
Hi,

Thanks for your good job. I want to ask how to plot the trajectories in scenes in your paper fig5  and how to find which frame corresponds to the scene at this time.?

I am very confused about the visualization about fig5. Can you tell me how to draw this kind of picture? Hope you can help me solve the questions. 

Best,
Jincan

**Comment by jun-long-li** [comment]
Hi,

Thanks for your interest and question!

We first draw trajectories with the same time step in a figure without scenes, and then look for the corresponding frame in the original video. Unfortunately, we don't have any trick to find an exact frame in the video, but fixing the scales and recording the frame numbers of figures will help.
